log_format cors_log
    '$remote_addr - $remote_user [$time_local] '
    '"$request" $status $body_bytes_sent '
    '"$http_origin" '
    '"$http_access_control_request_method" '
    '"$http_access_control_request_headers" '
    '"$sent_http_access_control_allow_origin" '
    '"$sent_http_access_control_allow_methods" '
    '"$sent_http_access_control_allow_headers" '
    '"$sent_http_access_control_allow_credentials" '
    '"$http_referer" '
    '"$http_user_agent"';


server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name qbdev.queuebuster.co;

    ssl_certificate /etc/letsencrypt/live/qbdev.queuebuster.co/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/qbdev.queuebuster.co/privkey.pem;

    access_log /var/log/nginx/cors_access.log cors_log;

    ssl_protocols TLSv1.2 TLSv1.3;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;

    server_tokens off;
  
location / {

    # Hide backend CORS headers which are comming backend
    proxy_hide_header Access-Control-Allow-Origin;
    proxy_hide_header Access-Control-Allow-Credentials;
    proxy_hide_header Access-Control-Allow-Methods;
    proxy_hide_header Access-Control-Allow-Headers;


    if ($request_method = OPTIONS) {
        return 204;
    }

    proxy_pass http://127.0.0.1:8003;
  }
}
server {
    listen 80;
    listen [::]:80;
    return 301 https://$host$request_uri;
}
